var ButtonSkin = {};
ButtonSkin.def = {
	borderWidth:[1,1,1,1],
	borderRadius:[5,5,5,5],
	cursor:"pointer",
	horizontal:true,
	defaults:{
		captionWidth:false,
		minWidth:30,
		minHeight:30,
	},
	hovered:{
		style:{
			disabled:{
				borderColor:"#ccc",
				backgroundColor:"#f6f6f6"
			},
			enabled:{
				backgroundColor:"#fdf5ce",
				borderColor:"#c77405"
			}
		}
	},
	style:{
		disabled:{
			borderColor:"#ccc",
			backgroundColor:"#f6f6f6"
		},
		enabled:{
			borderColor:"#ccc",
			backgroundColor:"#f6f6f6"
		}
	},
	c:[
	   {
		   hAlign:BoxElement.ALIGN.middle,
		   name:"caption",
		   padding:[6,4,0,4],
		   color:"#1c94c4",
		   hs:true
		   
	   }
	  ]
};

ButtonSkin.img = {
		borderColor:"#ccc",
		borderWidth:[1,1,1,1],
		borderRadius:[5,5,5,5],
		cursor:"pointer",
		horizontal:true,
		defaults:{
			minWidth:30,
			minHeight:30,
		},
		hovered:{
			style:{
				disabled:{
					borderColor:"#ccc",
					color:"#ccc",
					backgroundColor:"#f6f6f6"
				},
				enabled:{
					borderColor:"#c77405",
					color:"#ccc",
					backgroundColor:"#fdf5ce"
				}
			}
		},
		style:{
			disabled:{
				borderColor:"#ccc",
				color:"#ccc",
				backgroundColor:"#f6f6f6"
			},
			enabled:{
				borderColor:"#ccc",
				color:"#ccc",
				backgroundColor:"#f6f6f6"
			}
		},
		name:"img",
		backgroundPosition:"center center",
		backgroundRepeat:"no-repeat"
		/*c:[
		   {
			   vAlign:BoxElement.ALIGN.middle,
			   hAlign:BoxElement.ALIGN.middle,
			   name:"img",
			   width:16,
			   height:16,
			   margin:[0,0,0,6]
		   }
		]*/
};
ButtonSkin.link = {
	defaults:{
		captionWidth:false
	},
	horizontal:true,
	cursor:"pointer",
	c:[
	   {
		   name:"img",
		   width:16,
		   height:16
	   },
	   {
		   //margin:[5,0,0,3],
		   name:"caption",
		   hs:true,
		   textDecoration:"none",
		   color:"rgb(0, 0, 238)",
		   hovered:{
			   textDecoration:"underline"
		   }
	   }
	]
};

ButtonSkin.imgButton = {
		borderWidth:[1,1,1,1],
		borderRadius:[5,5,5,5],
		cursor:"pointer",
		horizontal:true,
		vAlign:BoxElement.ALIGN.middle,
		defaults:{
			minWidth:30,
			minHeight:30,
			captionWidth:false
		},
		hovered:{
			style:{
				disabled:{
					borderColor:"#ccc",
					backgroundColor:"#f6f6f6"
				},
				enabled:{
					backgroundColor:"#fdf5ce",
					borderColor:"#c77405"
				}
			}
		},
		style:{
			disabled:{
				borderColor:"#ccc",
				backgroundColor:"#f6f6f6"
			},
			enabled:{
				borderColor:"#ccc",
				backgroundColor:"#f6f6f6"
			}
		},
		c:[
		   {
			   hAlign:BoxElement.ALIGN.middle,
			   name:"caption",
               height:15,
			   color:"#1c94c4",
			   hs:true
		   },
		   {
			   name:"img",
			   width:22,
			   height:22,
			   vAlign:BoxElement.ALIGN.middle
		   }
		  ]
	};